// autogenerated by reconstant - do not edit!

// constants

// enums
export const SomeEnum = {
	A: "Primer mensaje de error",
	B: "Segundo mensaje de error",
	C: 8,
	D: "asdf",
}
export const OtherEnum = {
	FOO: "asdf",
	BAR: "qwerty",
}
