// autogenerated by reconstant - do not edit!

// constants
export const SOME_CONSTANT = "this is a constant string"
export const OTHER_CONSTANT = 42

// enums
export const SomeEnum = {
	A: "Primer mensaje de error",
	B: "Segundo mensaje de error",
	C: 8,
}
export const OtherEnum = {
	FOO: "asdf",
	BAR: "qwerty",
}
