# autogenerated by reconstant - do not edit!
from enum import Enum

# constants

# enums
class SomeEnum(Enum):
	A = "Primer mensaje de error"
	B = "Segundo mensaje de error"
	C = 8
	D = "asdf"
	E = "qwerty"

class OtherEnum(Enum):
	FOO = "asdf"
	BAR = "qwerty"

